### ISSUE TITLE
`C-SPC :e<enter>` leaves liquid unusable

### ISSUE THREAD

**Issue by xificurC** [mogenslund/liquid#45] opened 2020-05-14 19:05 UTC

**Comment by mogenslund** [comment] 2020-05-14 19:26
To get more information about the error a trick is to start liquid with --jframe and reproduce the error. This will allow the error message to print to the terminal, since the editor uses the JFrame.

**Comment by mogenslund** [comment] 2021-10-16 20:20
Yes. This has been fixed. I will close the issue.

**Closed by mogenslund** 2021-10-16 20:20 UTC
